### ISSUE TITLE
Platform supporting P-state controls

### ISSUE THREAD

**Issue by eastep** [geopm/geopm#73] opened 2016-11-14 22:02 UTC
Platform supporting P-state controls. Per-core P-state controls on products that support it. This should probably not support RAPL simultaneously.

**Comment by cmcantalupo** [comment] 2016-11-14 22:23
This is a duplicate of issue #11.

**Closed** 2016-11-14 22:23 UTC
Labels: enhancement

**Comment by eastep** [comment] 2016-11-14 22:37
Didn't see it because issue#11 had no associated milestone. Proposing inclusion in v0.3.0
