### ISSUE TITLE
GOMP/pthread interaction broken

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#163] opened 2018-02-06 20:20 UTC
Building with the GNU toolchain and attempting to use the pthread launch mechanism for the controller is currently broken.  The current workaround is to remove OMP_PROC_BIND from the launch line, but this may introduce other issues.  The current error is:

    Error: Invalid argument: Controller::pthread(): pthread_create() failed: at geopm/src/Controller.cpp:515
    Invalid argumentERROR: /home/bgeltz/geopm/.libs/geopmbench: Invalid argument

**Comment by dianarg** [comment] 2020-03-18 15:53
Is this related/duplicate of #987 ?

**Comment by dianarg** [comment] 2020-04-01 00:08
Fixed

**Closed by dianarg** 2020-04-01 00:08 UTC
Labels: bug, bug-exposure-low, bug-priority-low, bug-quality-high, bug-verification-required, build
