### ISSUE TITLE
geopmread broken for certain signals

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#363] opened 2018-09-21 00:10 UTC
```
$ geopmread POWER_PACKAGE package 0
Error: cannot read signal: <geopm> Invalid argument: PlatformIO::signal_domain_type(): signal name "REGION_ID#" not found: at geopm/src/PlatformIO.cpp:151
```

```
$ geopmread POWER_DRAM board_memory 0
Error: cannot read signal: <geopm> Invalid argument: PlatformIO::signal_domain_type(): signal name "REGION_ID#" not found: at geopm/src/PlatformIO.cpp:151
```

**Comment by dianarg** [comment] 2018-09-21 00:11
Possibly related/duplicate of #266

**Comment by dianarg** [comment] 2018-10-31 22:45
Once #266 is implemented, geopmread can have special handling for POWER_* signals that collects multiple samples over a period of time.  The last sample will be the most accurate.

**Closed** 2018-11-07 18:39 UTC
Labels: 1.0, bug
