### ISSUE TITLE
geopmanalysis not working in sbatch on quartz

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#171] opened 2018-02-22 18:15 UTC
Launching geopmanalysis inside an sbatch script results in issues that seem related to the PATH and LD_LIBRARY_PATH.  For starters, the system cannot find `lscpu` when the Launcher tries to execute it even though it's part of the PATH.  If you hardcode the path, `/usr/bin/lscpu`, then things work fine.

After that, the libraries that in the `LD_LIBRARY_PATH` fail to load when the app binary needs them because they cannot be found.  It's acting like the launcher.py is swallowing the environment when it calls `subprocess.Popen`.  I (Brad) wrote a small set of scripts yesterday in an attempt to isolate this issue with `lscpu` but was not successful.  More debug is necessary.  This also needs investigated on Mr. Fusion,

**Comment by bgeltz** [comment] 2018-02-27 19:13
This magically started working after 1550 PST on 2/22.  It had been failing every time before that.  I'm still not sure what changed.  I'll monitor for a few more days and close.  Still waiting on an explanation from the sysadmins.

**Comment by bgeltz** [comment] 2018-03-07 19:38
Closing this one.  No explanation from the sys admins.  I cannot reproduce the issue any longer.

**Closed by bgeltz** 2018-03-07 19:38 UTC
Labels: bug
