### ISSUE TITLE
EnergyEfficientAgent and FrequencyMapAgent should ignore very short regions

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#574] opened 2019-04-08 21:47 UTC
If the region runtimes are very close to the sample rate, the frequency setting applied will affect the next region as much as if not more than the current region, potentially degrading performance.   The Agent should not lower frequency in this case.

**Comment by bakerbrandond** [comment] 2019-04-08 21:58
dupe of #125

**Closed by bakerbrandond** 2019-04-08 21:58 UTC
Labels: 1.0, bug
